### ISSUE TITLE
結果を再現できない

### ISSUE THREAD

**Issue by tatuRD** [musyoku/wavenet#4]
初めまして。
現在WaveNetの勉強をしており、こちらのプログラムを参考にしているのですが、結果を再現できません。

こちらのプログラムを用いて、#1 で書かれていたyoutubeの動画の音声を8000Hzにダウンサンプリングして学習させてみたのですが、ノイズ混じりの中途半端な音声しか生成できませんでした。

学習や音声を生成する際のパラメータは、初期設定とは別の値を設定をしているのでしょうか？
また、学習のエポック数などに何か変更点があれば、その詳細を教えて頂けませんでしょうか？

**Comment by musyoku** [comment]
こんにちは
実は私の手元のコードでも再現できなくなっており原因を調べています
分かり次第お知らせします

**Comment by musyoku** [comment]
再現できたのでその時の状態のままのコードで更新しておきました。
またChainer 1.21に対応するためにいくつかコードを変更し、前処理を追加してあります。

WaveNetは非常に計算量の多いモデルのため当時の私の環境では実験を行うことが難しく、実装したもののほとんど実験せず放置していましたが、あらためて音声を学習させたところいくつかの知見が得られました。

### 前処理について

学習させる音声の無音部分はなるべく取り除く必要があります。

WaveNetは固定長入力のため、最初の音声信号を生成するためにダミーの入力信号列（無音で埋めたもの）を使うのですが、学習に使った音声データに無音部分がある場合、WaveNetがこれを学習し、生成時に無音しか出力されない現象が起きます。

そのため`data.py`に音声データの前後の無音部分を取り除くコードを追加しておきました。

### 学習率について

学習率の調整を要することがわかったので、ファイルに直書きしていた部分を消し、実行時にコマンドライン引数として指定する形に変更しました。

まず学習初期は`0.001`に設定し、誤差のオーダーが`e-01`以下になるか、単調減少していたものが増加してしまった場合に一度実行を止め、学習率を`0.00001`にして学習を再開するとうまくいきます。

初めに大きな学習率で一気に進めてから、小さな学習率に設定しなおして収束するまで学習します。

最適化手法としてはadamを使いますが、[eve](https://github.com/pfnet/chainer/pull/1847)も使えるようになっています。

eveは収束が非常に早いのですが、論文に誤りがあったらしくまだChainerにマージされていません。

実際にeveを用いて学習するとadamより収束が速いです。

今回のファミマの例では80epoch学習させました。

これはGTX1080で80分、GTX970で250分かかりました。

誤差のオーダーが`e-04`以下になると生成ができるようになります。

### ネットワーク構造について

WaveNetの開発者であるHeiga Zen氏によると、以下のネットワーク構造を用いたそうです。

![wavenet](https://pbs.twimg.com/media/C4xfueRWIAAtrwJ.png)

個人の環境ではGPU1台のメモリに乗らないので、私が実験を行った時は30ブロックを1ブロックに減らしました。（`model.py`の設定をそのまま使います）

ブロックを減らすと受容野（receptive field）が小さくなりますが、128ミリ秒（1024ステップ）の幅でもうまく生成できました。

またWaveNetの論文には実装に関する記述がないため、畳み込み時にバイアスを使うべきかどうかが分かりません。

私の実装には2割ほど想像で書いた部分が入っており、あまり自信がありません。

### 生成について

生成した音声です。

[5sec](https://drive.google.com/open?id=0ByQaxyG1S5JRbWpsdHFIeUVJb0U)
[20sec（失敗例）](https://drive.google.com/open?id=0ByQaxyG1S5JRelBGcVVnUS00X1k)

音声生成は失敗することもあります。

私の実装では、上記のように入力信号列として無音信号を用いて最初の時刻の信号を生成し、生成された信号を入力信号列に追加し、それをさらにWaveNetに入力し次の時刻の信号を生成する、という流れで生成しています。

Githubにある他の方の実装では、実際の音声信号の最初の数ステップを入力として、その先をWaveNetに生成させるものもありました。

Residualブロックを積んで受容野の幅を広げるとうまくいくかもしれません。

### 関連研究

[SampleRNN](https://arxiv.org/abs/1612.07837)や[Char2Wav](http://josesotelo.com/speechsynthesis/)など、より高速なモデルも提案されています。
